### ISSUE TITLE
demo down

### ISSUE THREAD

**Issue by lyonsun** [0k/multidomain-sso#1]
Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in /opt/apps/php-oe-json/src/OpenERP.php on line 5 Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /opt/apps/php-oe-json/src/OpenERP.php on line 5

**Comment by vaab** [comment]
Fixed. Well, I would appreciate a confirmation from your end.

**Comment by lyonsun** [comment]
Tested working. Thanks a lot.

**Comment by alexanderglueck** [comment]
Demo is down again.

**Comment by vaab** [comment]
Thanks for the feedback. It is fixed. It might undergo some other issues with correct online status in the very close future and come back to normal just after. If you can confirm it is working on your end, I'll appreciate.
