### ISSUE TITLE
Facing problem while implementing SSO

### ISSUE THREAD

**Issue by SherBahadurTudip** [0k/multidomain-sso#2]
Can you please provide me any document for the same.

I had implemented all three libraries, I am able to login to multiple domains while entering login credentials in one domain.

**_Logout is not working!_**

Please suggest what to do now, it's urgent, I have to implement the same in my one of my project.

Where we include Tikova library and how we can use it?

**Comment by vaab** [comment]
Sorry for the late answer. I won't have time to answer you in details to such a broad inquiry. What is your issue ? Logout is not working ? It is working on the demo.

If you are asking me to help you on your project, I'm afraid that I'm way to occupied currently to answer favorably to your request. Sorry for that :-)

The full source is ready for access through github, I do not see what else document you might need. Please be more specific.

I'm closing this thread as it doesn't seem to be an issue on the current implementation provided here.

``Tivoka`` is installed thanks ``composer`` when you install ``php-oe-json`` as it is one of its dependency. The actual ``README.rst`` of ``php-oe-json`` goes into enough detail about the installation process.
