### ISSUE TITLE
is it logout work?

### ISSUE THREAD

**Issue by dolphinotaku** [0k/multidomain-sso#3]
I visit http://foo.demo.0k.io and http://bar.demo.0k.io on my chrome,
login on http://bar.demo.0k.io
refresh http://foo.demo.0k.io, it can recognized me and already signed in
then I logout on http://bar.demo.0k.io
refresh http://foo.demo.0k.io, it still can recognized me and already signed in

Is it unexpected or just not implemented?

the screen cap as below
![bar demo 0k io](https://user-images.githubusercontent.com/5440966/48988344-fe927b80-f15f-11e8-8783-ab3598e6a4eb.png)
![foo demo 0k io](https://user-images.githubusercontent.com/5440966/48988345-ff2b1200-f15f-11e8-8307-835aae9d93f7.png)

**Comment by vaab** [comment]
Yes, it is unexpected, and I can't reproduce what you get on the last Firefox and Chrome I have at hand.

To be very clear, the last step is unexpected, and once un-logged from one of the site, the other should be un-logged too.

I was very careful reproducing your exact walk-through, and checked both screenshots, and everything seems ok except on the second screenshot (on URL foo.demo.0k.io)... 

why do you have some form data hanging there ?

It seems you have hit Ctrl-R, and accepted resending some form values to the page. Could that explain your issue ?

**Comment by dolphinotaku** [comment]
haha, I think you are right. The walk-through goes normal when I don't resend the form data. I will enjoy your source, thx.
